const BASE_URL="http://127.0.0.1:3000/"
const SIGNUP_URL=BASE_URL+"signup"
const LOGIN_URL=BASE_URL+"login"
const ADD_NEW_SERVICE_URL=BASE_URL+"add-new-service"
const GET_ALL_CREATED_SERVICES_URL=BASE_URL+"get-all-created-services"
const GET_DETAILS_OF_SERVICE=BASE_URL+"get-slots-created-service"
const SEARCH_URL=BASE_URL+"search-services"
const GET_NEWEST_SERVICES=BASE_URL+"newest-services"
const GET_CLIENT_SLOTS_OF_A_SERVICE=BASE_URL+"get-slots-client-service"
const CLIENT_REQUEST_SERVICE_SLIOT_URL=BASE_URL+"request-service"
const GET_ALL_CLIENT_REQUESTED_SERVICES=BASE_URL+"getall-requested-services"
const CANSEL_REQUESTED_SERVICE=BASE_URL+"cancel-requested-service"
const DELETE_SERVICE=BASE_URL+"delete-service"
const APPROVE_CLIENT_REQUEST=BASE_URL+"approve-client"
const REMOVE_CLIENT_REQUEST=BASE_URL+"remove-client"


export {SIGNUP_URL,LOGIN_URL,ADD_NEW_SERVICE_URL,GET_ALL_CREATED_SERVICES_URL,GET_DETAILS_OF_SERVICE,SEARCH_URL,GET_NEWEST_SERVICES,GET_CLIENT_SLOTS_OF_A_SERVICE,CLIENT_REQUEST_SERVICE_SLIOT_URL,GET_ALL_CLIENT_REQUESTED_SERVICES,CANSEL_REQUESTED_SERVICE,DELETE_SERVICE,APPROVE_CLIENT_REQUEST,REMOVE_CLIENT_REQUEST}